name: NuGet Generation for AspNetCore

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v2
        with:
          source-url: https://nuget.pkg.github.com/RichardvZyl/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}        
          
      - name: Build solution and generate NuGet package
        run: |  
          cd AspNetCore
          dotnet pack -c Release -o out  

      - name: Push generated package to GitHub registry
        run: dotnet nuget push ./AspNetCore/out/*.nupkg --setApiKey ${{secrets.NUGET_API_KEY}} --skip-duplicate --no-symbols
