name: NuGet Generation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v2
        with:
          source-url: https://nuget.pkg.github.com/RichardvZyl/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}        
          
      - name: Build solution and generate NuGet package
        run: |  
          cd AspNetCore
          dotnet pack -c Release -o out  

      - name: Push generated AspNetCore package to GitHub registry
        run: dotnet nuget push ./AspNetCore/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
        
      - name: Push generated AuditTrail package to GitHub registry
        run: dotnet nuget push ./AuditTrail/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
        
      - name: Push generated Concurrency package to GitHub registry
        run: dotnet nuget push ./Concurrency/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
        
      - name: Push generated Domain package to GitHub registry
        run: dotnet nuget push ./Domain/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
        
      - name: Push generated Entitlement package to GitHub registry
        run: dotnet nuget push ./Entitlement/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
        
      - name: Push generated EntityFrameworkCore package to GitHub registry
        run: dotnet nuget push ./EntityFrameworkCore/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
        
      - name: Push generated Extensions package to GitHub registry
        run: dotnet nuget push ./Extensions/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
        
      - name: Push generated IoC package to GitHub registry
        run: dotnet nuget push ./IoC/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
        
      - name: Push generated Logging package to GitHub registry
        run: dotnet nuget push ./Logging/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
        
      - name: Push generated Objects package to GitHub registry
        run: dotnet nuget push ./Objects/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
        
      - name: Push generated Regex package to GitHub registry
        run: dotnet nuget push ./Regex/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
        
      - name: Push generated Repositories package to GitHub registry
        run: dotnet nuget push ./Repositories/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
        
      - name: Push generated Results package to GitHub registry
        run: dotnet nuget push ./Results/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
        
      - name: Push generated Security package to GitHub registry
        run: dotnet nuget push ./Security/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
        
      - name: Push generated Swagger package to GitHub registry
        run: dotnet nuget push ./Swagger/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
        
      - name: Push generated Validator package to GitHub registry
        run: dotnet nuget push ./Validator/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}}
