name: NuGet Generation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v2
        with:
          source-url: https://nuget.pkg.github.com/RichardvZyl/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}        
          
      - name: Build solution and generate NuGet package
        run: dotnet pack -c Release -o out  

      - name: Push generated packages to GitHub registry
        run: |
          cd ../Abstractions/
          dotnet nuget push ./out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
        
      
